import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { transformSync } from "@babel/core";
import fs from "fs";
import path from "path";

/** esbuild plugin that runs babel-plugin-react-compiler on source .tsx/.ts files */
function reactCompilerPlugin() {
	return {
		name: "react-compiler",
		setup(build) {
			build.onLoad({ filter: /\.tsx?$/ }, (args) => {
				// Skip node_modules
				if (args.path.includes("node_modules")) return null;

				const source = fs.readFileSync(args.path, "utf8");
				const result = transformSync(source, {
					filename: args.path,
					presets: [
						"@babel/preset-typescript",
						["@babel/preset-react", { runtime: "automatic" }],
					],
					plugins: ["babel-plugin-react-compiler"],
					sourceMaps: "inline",
				});

				return {
					contents: result.code,
					loader: "js", // Babel already transformed TS+JSX → JS
					resolveDir: path.dirname(args.path),
				};
			});
		},
	};
}

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.tsx"],
	bundle: true,
	plugins: [reactCompilerPlugin()],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "esnext",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
